const API_CLIENT = import.meta.env.API_CLIENT;

export { API_CLIENT };

export const API_URL = import.meta.env.API_CLIENT;
export const COOKIE_ACCESS_TOKEN_KEY = import.meta.env.COOKIE_ACCESS_TOKEN_KEY;

export enum STATUS {
  NO = 'NO',
  USER_INFO = 'USER_INFO',
  CREATE_PROJECT = 'CREATE_PROJECT',
  UPDATE_PROJECT = 'UPDATE_PROJECT',
  DELETE_PROJECT = 'DELETE_PROJECT',
  USER_STORY = 'USER_STORY',
  GET_USER_STORY_LIST = 'GET_USER_STORY_LIST',
  UPDATE_USER_STORY = 'UPDATE_USER_STORY',
  DELETE_USER_STORY = 'DELETE_USER_STORY',
  CREATE_USER_STORY = 'CREATE_USER_STORY',
  USE_CASE = 'USE_CASE',
  UPDATE_USE_CASE = 'UPDATE_USE_CASE',
  DELETE_USE_CASE = 'DELETE_USE_CASE',
  CREATE_USE_CASE = 'CREATE_USE_CASE',
  TASK = 'TASK',
  GET_TASK = 'GET_TASK',
  CREATE_TASK = 'CREATE_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  DELETE_TASK = 'DELETE_TASK',
  SUB_TASK = 'SUB_TASK',
  GET_SUB_TASK_LIST = 'GET_SUB_TASK_LIST',
  CREATE_SUB_TASK = 'CREATE_SUB_TASK',
  UPDATE_SUB_TASK = 'UPDATE_SUB_TASK',
  DELETE_SUB_TASK = 'DELETE_SUB_TASK',
  VIEW_SUB_TASK = 'VIEW_SUB_TASK',
  WORK_LOG = 'WORK_LOG',
  CREATE_WORK_LOG = 'CREATE_WORK_LOG',
  UPDATE_WORK_LOG = 'UPDATE_WORK_LOG',
  DELETE_WORK_LOG = 'DELETE_WORK_LOG'
}

export enum POSITION {
  BE = 'BE',
  FE = 'FE',
  PM = 'PM'
}
